spring.application.name=sb-ecom

spring.h2.console.enabled = true
spring.datasource.url = jdbc:h2:mem:test

project.image = images/

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=mySecretKey123912738ujeachdjhbakjojnuihqjsdckjsdchfcgfxjfcghcfgvf
app.jwt.expiration=86400000

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.ecommerce.sb_ecom=DEBUG